### ISSUE TITLE
MaulingMonkey has crev-proofs!

### ISSUE THREAD

**Issue by MaulingMonkey** [Lokathor/crev-proofs#1]
If you're interested:  https://github.com/MaulingMonkey/crev-proofs

Full disclosure - I rate brutally and with strong opinions... anything with soundness issues gets rated "negative" (I'd use "dangerous" some too but that no longer exists!).  Or a history of abusing unsafe too much (sorry actix-\*!).  Or just because it makes me vaguely nervous (I should probably re-review redox_syscall and bump it up to neutral at least... it's *probably* OK for what it does... probably... I just don't have a great way to audit anything about it...)

**Comment by Lokathor** [comment]
Resolved in https://github.com/Lokathor/crev-proofs/commit/c88f70806b99a959d230dec8a4cfd67d833bdcf4
